name: Trigger auto deployment for container-app-ed4oggwuouyao

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-ed4oggwuouyao-AutoDeployTrigger-d85405db-4d75-4e28-b828-2a7da622e507.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPED4OGGWUOUYAO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPED4OGGWUOUYAO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPED4OGGWUOUYAO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPED4OGGWUOUYAO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPED4OGGWUOUYAO_REGISTRY_PASSWORD }}
          containerAppName: container-app-ed4oggwuouyao
          resourceGroup: todoappwithuserregistration8644
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


